### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nardiyansah** [nardiyansah/Journey-to-Express#1]
- [ ] Installing express
- [ ] Hello world
- [ ] Express generator
- [ ] Basic routing
- [ ] Static files
- [ ] Routing
- [ ] Writing middleware
- [ ] Using middleware
- [ ] Overriding the Express API
- [ ] Using templates engines
- [ ] Error handling
- [ ] Debugging
- [ ] Express behind proxies
- [ ] Database integration

next is [Advance topics](https://expressjs.com/en/advanced/developing-template-engines.html)
